name: Build libmpv-android

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Symlink SDK
        working-directory: ./buildscripts
        run: |
          mkdir sdk
          ln -s ${ANDROID_HOME} ./sdk/android-sdk-linux
      - name: Download dependencies
        working-directory: ./buildscripts
        run: ./download.sh
      - name: Apply patches
        working-directory: ./buildscripts
        run: ./patch.sh
      - name: Build
        working-directory: ./buildscripts
        run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: libmpv-release.aar
          path: ./libmpv/build/outputs/aar/libmpv-release.aar
